name: Release

on:
  push:
    tags:
      - "*"

env:
  DASHBOARD_VERSION: latest # replace with tag aka: "tags/v1.2.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: npx vite build --mode dashboard
      - run: npx vite build --mode graphics
      - run: zip -r ${{ github.event.repository.name }}.zip graphics package.json LICENSE
      - uses: svenstaro/upload-release-action@v2
        with:
          file: "${{ github.event.repository.name }}.zip"
          overwrite: true
